-- Hoikin Lam hlam13@calpoly.edu

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS Vocals;

DROP TABLE IF EXISTS Performance;

DROP TABLE IF EXISTS Instruments;

DROP TABLE IF EXISTS Tracklists;

DROP TABLE IF EXISTS Songs;

DROP TABLE IF EXISTS Albums;

DROP TABLE IF EXISTS Band;

SET FOREIGN_KEY_CHECKS = 1;