-- Hoikin Lam hlam13@calpoly.edu

INSERT INTO Songs (SongID, SongTitle) VALUES (1, 'Overture');
INSERT INTO Songs (SongID, SongTitle) VALUES (2, 'A Bar In Amsterdam');
INSERT INTO Songs (SongID, SongTitle) VALUES (3, 'Demon Kitty Rag');
INSERT INTO Songs (SongID, SongTitle) VALUES (4, 'Tea With Cinnamon');
INSERT INTO Songs (SongID, SongTitle) VALUES (5, 'Hey Ho on the Devil''s Back');
INSERT INTO Songs (SongID, SongTitle) VALUES (6, 'Wading in Deeper');
INSERT INTO Songs (SongID, SongTitle) VALUES (7, 'Le Pop');
INSERT INTO Songs (SongID, SongTitle) VALUES (8, 'Der Kapitan');
INSERT INTO Songs (SongID, SongTitle) VALUES (9, 'Virginia Clemm');
INSERT INTO Songs (SongID, SongTitle) VALUES (10, 'Play My Darling, Play');
INSERT INTO Songs (SongID, SongTitle) VALUES (11, 'To the Sea');
INSERT INTO Songs (SongID, SongTitle) VALUES (12, 'Mother Superior');
INSERT INTO Songs (SongID, SongTitle) VALUES (13, 'Ain''t no Thang');
INSERT INTO Songs (SongID, SongTitle) VALUES (14, 'A Kiss Before You Go');
INSERT INTO Songs (SongID, SongTitle) VALUES (15, 'I Will Dance (When I Walk Away)');
INSERT INTO Songs (SongID, SongTitle) VALUES (16, 'Cherry Pie');
INSERT INTO Songs (SongID, SongTitle) VALUES (17, 'Land of Confusion');
INSERT INTO Songs (SongID, SongTitle) VALUES (18, 'Lady Marlene');
INSERT INTO Songs (SongID, SongTitle) VALUES (19, 'Rock-Paper-Scissors');
INSERT INTO Songs (SongID, SongTitle) VALUES (20, 'Cocktails and Ruby Slippers');
INSERT INTO Songs (SongID, SongTitle) VALUES (21, 'Soviet Trumpeter');
INSERT INTO Songs (SongID, SongTitle) VALUES (22, 'Loathsome M');
INSERT INTO Songs (SongID, SongTitle) VALUES (23, 'Shepherd''s Song');
INSERT INTO Songs (SongID, SongTitle) VALUES (24, 'Gypsy Flee');
INSERT INTO Songs (SongID, SongTitle) VALUES (25, 'God''s Great Dust Storm');
INSERT INTO Songs (SongID, SongTitle) VALUES (26, 'Ouch');
INSERT INTO Songs (SongID, SongTitle) VALUES (27, 'Listening to the World');
INSERT INTO Songs (SongID, SongTitle) VALUES (28, 'Johnny Blowtorch');
INSERT INTO Songs (SongID, SongTitle) VALUES (29, 'Flash');
INSERT INTO Songs (SongID, SongTitle) VALUES (30, 'Driving After You');
INSERT INTO Songs (SongID, SongTitle) VALUES (31, 'My Own Tune');
INSERT INTO Songs (SongID, SongTitle) VALUES (32, 'Badlands');
INSERT INTO Songs (SongID, SongTitle) VALUES (33, 'Old De Spain');
INSERT INTO Songs (SongID, SongTitle) VALUES (34, 'Oh My God');
INSERT INTO Songs (SongID, SongTitle) VALUES (35, 'Lady Gray');
INSERT INTO Songs (SongID, SongTitle) VALUES (36, 'Shine Like Neon Rays');
INSERT INTO Songs (SongID, SongTitle) VALUES (37, 'Flash in the Dark');
INSERT INTO Songs (SongID, SongTitle) VALUES (38, 'My Dear');
INSERT INTO Songs (SongID, SongTitle) VALUES (39, 'Bad Girl');
INSERT INTO Songs (SongID, SongTitle) VALUES (40, 'Rockland');
INSERT INTO Songs (SongID, SongTitle) VALUES (41, 'Curvaceous Needs');
INSERT INTO Songs (SongID, SongTitle) VALUES (42, 'Borka');
INSERT INTO Songs (SongID, SongTitle) VALUES (43, 'Let it Snow');
