-- Hoikin Lam hlam13@calpoly.edu

INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (1, 'chevrolet', 'chevrolet chevelle malibu');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (2, 'buick', 'buick skylark 320');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (3, 'plymouth', 'plymouth satellite');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (4, 'amc', 'amc rebel sst');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (5, 'ford', 'ford torino');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (6, 'ford', 'ford galaxie 500');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (7, 'chevrolet', 'chevrolet impala');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (8, 'plymouth', 'plymouth fury iii');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (9, 'pontiac', 'pontiac catalina');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (10, 'amc', 'amc ambassador dpl');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (11, 'citroen', 'citroen ds-21 pallas');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (12, 'chevrolet', 'chevrolet chevelle concours (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (13, 'ford', 'ford torino (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (14, 'plymouth', 'plymouth satellite (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (15, 'amc', 'amc rebel sst (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (16, 'dodge', 'dodge challenger se');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (17, 'plymouth', 'plymouth cuda 340');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (18, 'ford', 'ford mustang boss 302');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (19, 'chevrolet', 'chevrolet monte carlo');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (20, 'buick', 'buick estate wagon (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (21, 'toyota', 'toyota corona mark ii');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (22, 'plymouth', 'plymouth duster');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (23, 'amc', 'amc hornet');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (24, 'ford', 'ford maverick');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (25, 'datsun', 'datsun pl510');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (26, 'volkswagen', 'volkswagen 1131 deluxe sedan');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (27, 'peugeot', 'peugeot 504');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (28, 'audi', 'audi 100 ls');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (29, 'saab', 'saab 99e');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (30, 'bmw', 'bmw 2002');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (31, 'amc', 'amc gremlin');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (32, 'ford', 'ford f250');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (33, 'chevrolet', 'chevy c20');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (34, 'dodge', 'dodge d200');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (35, 'hi', 'hi 1200d');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (36, 'datsun', 'datsun pl510');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (37, 'chevrolet', 'chevrolet vega 2300');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (38, 'toyota', 'toyota corona');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (39, 'ford', 'ford pinto');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (40, 'volkswagen', 'volkswagen super beetle 117');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (41, 'amc', 'amc gremlin');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (42, 'plymouth', 'plymouth satellite custom');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (43, 'chevrolet', 'chevrolet chevelle malibu');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (44, 'ford', 'ford torino 500');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (45, 'amc', 'amc matador');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (46, 'chevrolet', 'chevrolet impala');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (47, 'pontiac', 'pontiac catalina brougham');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (48, 'ford', 'ford galaxie 500');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (49, 'plymouth', 'plymouth fury iii');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (50, 'dodge', 'dodge monaco (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (51, 'ford', 'ford country squire (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (52, 'pontiac', 'pontiac safari (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (53, 'amc', 'amc hornet sportabout (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (54, 'chevrolet', 'chevrolet vega (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (55, 'pontiac', 'pontiac firebird');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (56, 'ford', 'ford mustang');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (57, 'mercury', 'mercury capri 2000');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (58, 'opel', 'opel 1900');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (59, 'peugeot', 'peugeot 304');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (60, 'fiat', 'fiat 124b');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (61, 'toyota', 'toyota corolla 1200');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (62, 'datsun', 'datsun 1200');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (63, 'volkswagen', 'volkswagen model 111');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (64, 'plymouth', 'plymouth cricket');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (65, 'toyota', 'toyota corona hardtop');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (66, 'dodge', 'dodge colt hardtop');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (67, 'volkswagen', 'volkswagen type 3');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (68, 'chevrolet', 'chevrolet vega');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (69, 'ford', 'ford pinto runabout');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (70, 'chevrolet', 'chevrolet impala');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (71, 'pontiac', 'pontiac catalina');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (72, 'plymouth', 'plymouth fury iii');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (73, 'ford', 'ford galaxie 500');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (74, 'amc', 'amc ambassador sst');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (75, 'mercury', 'mercury marquis');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (76, 'buick', 'buick lesabre custom');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (77, 'oldsmobile', 'oldsmobile delta 88 royale');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (78, 'chrysler', 'chrysler newport royal');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (79, 'mazda', 'mazda rx2 coupe');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (80, 'amc', 'amc matador (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (81, 'chevrolet', 'chevrolet chevelle concours (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (82, 'ford', 'ford gran torino (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (83, 'plymouth', 'plymouth satellite custom (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (84, 'volvo', 'volvo 145e (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (85, 'volkswagen', 'volkswagen 411 (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (86, 'peugeot', 'peugeot 504 (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (87, 'renault', 'renault 12 (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (88, 'ford', 'ford pinto (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (89, 'datsun', 'datsun 510 (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (90, 'toyota', 'toyota corona mark ii (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (91, 'dodge', 'dodge colt (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (92, 'toyota', 'toyota corolla 1600 (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (93, 'buick', 'buick century 350');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (94, 'amc', 'amc matador');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (95, 'chevrolet', 'chevrolet malibu');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (96, 'ford', 'ford gran torino');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (97, 'dodge', 'dodge coronet custom');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (98, 'mercury', 'mercury marquis brougham');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (99, 'chevrolet', 'chevrolet caprice classic');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (100, 'ford', 'ford ltd');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (101, 'plymouth', 'plymouth fury gran sedan');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (102, 'chrysler', 'chrysler new yorker brougham');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (103, 'buick', 'buick electra 225 custom');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (104, 'amc', 'amc ambassador brougham');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (105, 'plymouth', 'plymouth valiant');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (106, 'chevrolet', 'chevrolet nova custom');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (107, 'amc', 'amc hornet');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (108, 'ford', 'ford maverick');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (109, 'plymouth', 'plymouth duster');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (110, 'volkswagen', 'volkswagen super beetle');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (111, 'chevrolet', 'chevrolet impala');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (112, 'ford', 'ford country');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (113, 'plymouth', 'plymouth custom suburb');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (114, 'oldsmobile', 'oldsmobile vista cruiser');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (115, 'amc', 'amc gremlin');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (116, 'toyota', 'toyota carina');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (117, 'chevrolet', 'chevrolet vega');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (118, 'datsun', 'datsun 610');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (119, 'mazda', 'mazda rx3');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (120, 'ford', 'ford pinto');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (121, 'mercury', 'mercury capri v6');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (122, 'fiat', 'fiat 124 sport coupe');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (123, 'chevrolet', 'chevrolet monte carlo s');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (124, 'pontiac', 'pontiac grand prix');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (125, 'fiat', 'fiat 128');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (126, 'opel', 'opel manta');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (127, 'audi', 'audi 100ls');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (128, 'volvo', 'volvo 144ea');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (129, 'dodge', 'dodge dart custom');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (130, 'saab', 'saab 99le');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (131, 'toyota', 'toyota mark ii');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (132, 'oldsmobile', 'oldsmobile omega');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (133, 'plymouth', 'plymouth duster');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (134, 'ford', 'ford maverick');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (135, 'amc', 'amc hornet');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (136, 'chevrolet', 'chevrolet nova');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (137, 'datsun', 'datsun b210');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (138, 'ford', 'ford pinto');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (139, 'toyota', 'toyota corolla 1200');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (140, 'chevrolet', 'chevrolet vega');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (141, 'chevrolet', 'chevrolet chevelle malibu classic');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (142, 'amc', 'amc matador');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (143, 'plymouth', 'plymouth satellite sebring');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (144, 'ford', 'ford gran torino');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (145, 'buick', 'buick century luxus (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (146, 'dodge', 'dodge coronet custom (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (147, 'ford', 'ford gran torino (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (148, 'amc', 'amc matador (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (149, 'audi', 'audi fox');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (150, 'volkswagen', 'volkswagen dasher');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (151, 'opel', 'opel manta');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (152, 'toyota', 'toyota corona');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (153, 'datsun', 'datsun 710');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (154, 'dodge', 'dodge colt');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (155, 'fiat', 'fiat 128');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (156, 'fiat', 'fiat 124 tc');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (157, 'honda', 'honda civic');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (158, 'subaru', 'subaru');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (159, 'fiat', 'fiat x1.9');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (160, 'plymouth', 'plymouth valiant custom');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (161, 'chevrolet', 'chevrolet nova');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (162, 'mercury', 'mercury monarch');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (163, 'ford', 'ford maverick');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (164, 'pontiac', 'pontiac catalina');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (165, 'chevrolet', 'chevrolet bel air');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (166, 'plymouth', 'plymouth grand fury');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (167, 'ford', 'ford ltd');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (168, 'buick', 'buick century');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (169, 'chevrolet', 'chevrolet chevelle malibu');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (170, 'amc', 'amc matador');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (171, 'plymouth', 'plymouth fury');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (172, 'buick', 'buick skyhawk');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (173, 'chevrolet', 'chevrolet monza 2+2');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (174, 'ford', 'ford mustang ii');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (175, 'toyota', 'toyota corolla');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (176, 'ford', 'ford pinto');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (177, 'amc', 'amc gremlin');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (178, 'pontiac', 'pontiac astro');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (179, 'toyota', 'toyota corona');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (180, 'volkswagen', 'volkswagen dasher');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (181, 'datsun', 'datsun 710');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (182, 'ford', 'ford pinto');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (183, 'volkswagen', 'volkswagen rabbit');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (184, 'amc', 'amc pacer');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (185, 'audi', 'audi 100ls');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (186, 'peugeot', 'peugeot 504');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (187, 'volvo', 'volvo 244dl');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (188, 'saab', 'saab 99le');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (189, 'honda', 'honda civic cvcc');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (190, 'fiat', 'fiat 131');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (191, 'opel', 'opel 1900');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (192, 'capri', 'capri ii');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (193, 'dodge', 'dodge colt');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (194, 'renault', 'renault 12tl');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (195, 'chevrolet', 'chevrolet chevelle malibu classic');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (196, 'dodge', 'dodge coronet brougham');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (197, 'amc', 'amc matador');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (198, 'ford', 'ford gran torino');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (199, 'plymouth', 'plymouth valiant');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (200, 'chevrolet', 'chevrolet nova');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (201, 'ford', 'ford maverick');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (202, 'amc', 'amc hornet');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (203, 'chevrolet', 'chevrolet chevette');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (204, 'chevrolet', 'chevrolet woody');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (205, 'volkswagen', 'vw rabbit');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (206, 'honda', 'honda civic');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (207, 'dodge', 'dodge aspen se');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (208, 'ford', 'ford granada ghia');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (209, 'pontiac', 'pontiac ventura sj');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (210, 'amc', 'amc pacer d/l');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (211, 'volkswagen', 'volkswagen rabbit');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (212, 'datsun', 'datsun b-210');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (213, 'toyota', 'toyota corolla');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (214, 'ford', 'ford pinto');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (215, 'volvo', 'volvo 245');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (216, 'plymouth', 'plymouth volare premier v8');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (217, 'peugeot', 'peugeot 504');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (218, 'toyota', 'toyota mark ii');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (219, 'mercedes-benz', 'mercedes-benz 280s');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (220, 'cadillac', 'cadillac seville');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (221, 'chevrolet', 'chevy c10');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (222, 'ford', 'ford f108');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (223, 'dodge', 'dodge d100');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (224, 'honda', 'honda accord cvcc');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (225, 'buick', 'buick opel isuzu deluxe');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (226, 'renault', 'renault 5 gtl');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (227, 'plymouth', 'plymouth arrow gs');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (228, 'datsun', 'datsun f-10 hatchback');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (229, 'chevrolet', 'chevrolet caprice classic');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (230, 'oldsmobile', 'oldsmobile cutlass supreme');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (231, 'dodge', 'dodge monaco brougham');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (232, 'mercury', 'mercury cougar brougham');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (233, 'chevrolet', 'chevrolet concours');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (234, 'buick', 'buick skylark');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (235, 'plymouth', 'plymouth volare custom');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (236, 'ford', 'ford granada');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (237, 'pontiac', 'pontiac grand prix lj');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (238, 'chevrolet', 'chevrolet monte carlo landau');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (239, 'chrysler', 'chrysler cordoba');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (240, 'ford', 'ford thunderbird');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (241, 'volkswagen', 'volkswagen rabbit custom');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (242, 'pontiac', 'pontiac sunbird coupe');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (243, 'toyota', 'toyota corolla liftback');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (244, 'ford', 'ford mustang ii 2+2');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (245, 'chevrolet', 'chevrolet chevette');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (246, 'dodge', 'dodge colt m/m');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (247, 'subaru', 'subaru dl');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (248, 'volkswagen', 'volkswagen dasher');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (249, 'datsun', 'datsun 810');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (250, 'bmw', 'bmw 320i');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (251, 'mazda', 'mazda rx-4');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (252, 'volkswagen', 'volkswagen rabbit custom diesel');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (253, 'ford', 'ford fiesta');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (254, 'mazda', 'mazda glc deluxe');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (255, 'datsun', 'datsun b210 gx');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (256, 'honda', 'honda civic cvcc');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (257, 'oldsmobile', 'oldsmobile cutlass salon brougham');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (258, 'dodge', 'dodge diplomat');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (259, 'mercury', 'mercury monarch ghia');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (260, 'pontiac', 'pontiac phoenix lj');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (261, 'chevrolet', 'chevrolet malibu');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (262, 'ford', 'ford fairmont (auto)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (263, 'ford', 'ford fairmont (man)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (264, 'plymouth', 'plymouth volare');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (265, 'amc', 'amc concord');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (266, 'buick', 'buick century special');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (267, 'mercury', 'mercury zephyr');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (268, 'dodge', 'dodge aspen');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (269, 'amc', 'amc concord d/l');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (270, 'chevrolet', 'chevrolet monte carlo landau');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (271, 'buick', 'buick regal sport coupe (turbo)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (272, 'ford', 'ford futura');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (273, 'dodge', 'dodge magnum xe');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (274, 'chevrolet', 'chevrolet chevette');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (275, 'toyota', 'toyota corona');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (276, 'datsun', 'datsun 510');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (277, 'dodge', 'dodge omni');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (278, 'toyota', 'toyota celica gt liftback');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (279, 'plymouth', 'plymouth sapporo');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (280, 'oldsmobile', 'oldsmobile starfire sx');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (281, 'datsun', 'datsun 200-sx');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (282, 'audi', 'audi 5000');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (283, 'volvo', 'volvo 264gl');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (284, 'saab', 'saab 99gle');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (285, 'peugeot', 'peugeot 604sl');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (286, 'volkswagen', 'volkswagen scirocco');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (287, 'honda', 'honda accord lx');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (288, 'pontiac', 'pontiac lemans v6');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (289, 'mercury', 'mercury zephyr 6');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (290, 'ford', 'ford fairmont 4');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (291, 'amc', 'amc concord dl 6');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (292, 'dodge', 'dodge aspen 6');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (293, 'chevrolet', 'chevrolet caprice classic');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (294, 'ford', 'ford ltd landau');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (295, 'mercury', 'mercury grand marquis');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (296, 'dodge', 'dodge st. regis');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (297, 'buick', 'buick estate wagon (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (298, 'ford', 'ford country squire (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (299, 'chevrolet', 'chevrolet malibu classic (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (300, 'chrysler', 'chrysler lebaron town @ country (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (301, 'volkswagen', 'vw rabbit custom');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (302, 'mazda',  'mazda glc deluxe');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (303, 'dodge', 'dodge colt hatchback custom');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (304, 'amc', 'amc spirit dl');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (305, 'mercedes', 'mercedes benz 300d');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (306, 'cadillac', 'cadillac eldorado');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (307, 'peugeot', 'peugeot 504');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (308, 'oldsmobile', 'oldsmobile cutlass salon brougham');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (309, 'plymouth', 'plymouth horizon');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (310, 'plymouth', 'plymouth horizon tc3');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (311, 'datsun', 'datsun 210');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (312, 'fiat', 'fiat strada custom');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (313, 'buick', 'buick skylark limited');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (314, 'chevrolet', 'chevrolet citation');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (315, 'oldsmobile', 'oldsmobile omega brougham');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (316, 'pontiac', 'pontiac phoenix');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (317, 'volkswagen', 'vw rabbit');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (318, 'toyota', 'toyota corolla tercel');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (319, 'chevrolet', 'chevrolet chevette');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (320, 'datsun', 'datsun 310');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (321, 'chevrolet', 'chevrolet citation');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (322, 'ford', 'ford fairmont');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (323, 'amc', 'amc concord');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (324, 'dodge', 'dodge aspen');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (325, 'audi', 'audi 4000');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (326, 'toyota', 'toyota corona liftback');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (327, 'mazda', 'mazda 626');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (328, 'datsun', 'datsun 510 hatchback');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (329, 'toyota', 'toyota corolla');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (330, 'mazda', 'mazda glc');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (331, 'dodge', 'dodge colt');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (332, 'datsun', 'datsun 210');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (333, 'volkswagen', 'vw rabbit c (diesel)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (334, 'volkswagen', 'vw dasher (diesel)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (335, 'audi', 'audi 5000s (diesel)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (336, 'mercedes-benz', 'mercedes-benz 240d');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (337, 'honda', 'honda civic 1500 gl');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (338, 'renault', 'renault lecar deluxe');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (339, 'subaru', 'subaru dl');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (340,  'volkswagen', 'volkswagen rabbit');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (341, 'datsun', 'datsun 280-zx');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (342, 'mazda', 'mazda rx-7 gs');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (343, 'triumph', 'triumph tr7 coupe');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (344, 'ford', 'ford mustang cobra');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (345, 'honda', 'honda accord');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (346, 'plymouth', 'plymouth reliant');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (347, 'buick', 'buick skylark');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (348, 'dodge', 'dodge aries wagon (sw)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (349, 'chevrolet', 'chevrolet citation');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (350, 'plymouth', 'plymouth reliant');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (351, 'toyota', 'toyota starlet');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (352, 'plymouth', 'plymouth champ');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (353, 'honda', 'honda civic 1300');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (354, 'subaru', 'subaru');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (355, 'datsun', 'datsun 210 mpg');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (356, 'toyota', 'toyota tercel');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (357, 'mazda', 'mazda glc 4');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (358, 'plymouth', 'plymouth horizon 4');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (359, 'ford', 'ford escort 4w');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (360, 'ford', 'ford escort 2h');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (361, 'volkswagen', 'volkswagen jetta');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (362, 'renault', 'renault 18i');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (363, 'honda', 'honda prelude');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (364, 'toyota', 'toyota corolla');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (365, 'datsun', 'datsun 200sx');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (366, 'mazda', 'mazda 626');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (367, 'peugeot', 'peugeot 505s turbo diesel');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (368, 'saab', 'saab 900s');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (369, 'volvo', 'volvo diesel');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (370, 'toyota', 'toyota cressida');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (371, 'datsun', 'datsun 810 maxima');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (372, 'buick', 'buick century');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (373, 'oldsmobile', 'oldsmobile cutlass ls');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (374, 'ford', 'ford granada gl');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (375, 'chrysler', 'chrysler lebaron salon');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (376, 'chevrolet', 'chevrolet cavalier');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (377, 'chevrolet', 'chevrolet cavalier wagon');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (378, 'chevrolet', 'chevrolet cavalier 2-door');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (379, 'pontiac', 'pontiac j2000 se hatchback');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (380, 'dodge', 'dodge aries se');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (381, 'pontiac', 'pontiac phoenix');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (382, 'ford', 'ford fairmont futura');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (383, 'amc', 'amc concord dl');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (384, 'volkswagen', 'volkswagen rabbit l');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (385, 'mazda', 'mazda glc custom l');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (386, 'mazda', 'mazda glc custom');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (387, 'plymouth', 'plymouth horizon miser');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (388, 'mercury', 'mercury lynx l');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (389, 'nissan', 'nissan stanza xe');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (390, 'honda', 'honda accord');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (391, 'toyota', 'toyota corolla');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (392, 'honda', 'honda civic');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (393, 'honda', 'honda civic (auto)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (394, 'datsun', 'datsun 310 gx');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (395, 'buick', 'buick century limited');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (396, 'oldsmobile', 'oldsmobile cutlass ciera (diesel)');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (397, 'chrysler', 'chrysler lebaron medallion');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (398, 'ford', 'ford granada l');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (399, 'toyota', 'toyota celica gt');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (400, 'dodge', 'dodge charger 2.2');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (401, 'chevrolet', 'chevrolet camaro');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (402, 'ford', 'ford mustang gl');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (403, 'volkswagen', 'vw pickup');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (404, 'dodge', 'dodge rampage');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (405, 'ford', 'ford ranger');
INSERT INTO Car_Names (MakeID, ModelName, MakeDescription) VALUES (406, 'chevrolet', 'chevy s-10');
